config/routes.rb
Rails.application.routes.draw do
  get 'page/index'

  resources :sessions, only: [:new, :create, :destroy]  
  get 'signup', to: 'users#new', as: 'signup'  
  get 'login', to: 'sessions#new', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'  
  get 'forgot', to: 'login#forgotPassword'

  resources :users
  get 'joinOrganisation', to: 'users#joinOrganisation'
  get 'leaveOrganisation', to: 'users#leaveOrganisation'

  resources :organisations

  resources :shifts
  get 'shift/index'
  get 'shift/create'

  root 'page#index'  
end

app/models/user.rb
class User < ApplicationRecord
    has_one :organisation
    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/controllers/_users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
    @user = User.new(user_params)
    # Set organistationId to 0 to know its not assigned
    @user.organisation_id = 0
    @passwordConfirm = params[:passwordConfirm]

    #password match validation

    if @user.save   
      session[:user_id] = @user.id   
      redirect_to root_url, notice: 'User successfully created.'   
    else   
      render :new   
    end   

  end
   
  def show
    @user = User.find(params[:id])

    if @user.organisation_id==0
      @organisations = Organisation.all
      render template: "users/noOrganisation" 
    else
      @organisation = Organisation.find(@user.organisation_id)
    end

  end

  

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    redirect_to action: "show", id: session[:user_id]
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    if @user.organisation_id==0
      @organisations = Organisation.all
      render template: "users/noOrganisation" 
    else
      @organisation = Organisation.find(@user.organisation_id)
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.organisation_id=0
      if @user.save
        redirect_to new_session_path, email: @user.email, password: @user.password, notice: 'User was successfully created. Now you can log in'
      else
        render :new,  notice: 'Something went wrong, please contact your system admin'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def joinOrganisation
    @user = User.find(params[:user_id])
    @organisation = Organisation.find(params[:organisation_id])
    # Update user with organisation id
    @user.organisation_id = @organisation.id
    @user.save
    redirect_to @user
  end

  def leaveOrganisation
    @user = User.find(params[:userId])
    # Remove organisation id
    @user.organisation_id = 0
    @user.save
    redirect_to @user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:organisation_id, :name, :email, :password, :password_confirmation)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Log in', sessions_path %> <br>

app/views/users/_show.html.erb
<%= render 'show' %>  

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Adnat</h1>
<h2>Sign up</h2>
<%= form_with scope: :user, url: users_path, local: true do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :email %><br>
      <%= form.email_field :email %>
    </p>
   
    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
        <%= form.label "Confirm Password" %><br>
        <%= form.password_field :passwordConfirm %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'Log in', login_index_path %> <br>

app/views/users/noOrganisation.html.erb
<p> 
Whoa, hold up there bud.<br>
You don''t seem to be a member of any organistations. <br>
You can join an existing one or create your own.
</p>

<h2>Organisations</h2>
<% @organisations.each do |organisation| %>
    <tr>
      <td><%= organisation.name %></td> 
      <%= link_to 'Edit', edit_organisation_url(organisation) %>
      <%= link_to 'Join', joinOrganisation_path(organisation_id: organisation.id, user_id: @user.id) %>
      <%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %> <br>
    </tr>
  <% end %>

<h2>Create organistaion</h2>
<%= form_with scope: :organisation, url: organisations_path, local: true do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label "Hourly rate" %><br>
      <%= form.text_field :hourly_rate %>
    </p>
      
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/users/show.html.erb
<h2><%= @organisation.name %></h2>
<%= link_to 'View Shifts', shifts_url(organisation_id: @organisation.id) %> 
<%= link_to 'Edit', edit_organisation_url(@organisation) %>
<%= link_to 'Leave', leaveOrganisation_path(userId: @user.id) %>